import { AIRBNBimages } from "../assets";

const HomesData = [
  {
    id: 1,
    title: " Ngaparou, Senegal",
    distanceAway: 2403,
    startDate: "Sept 30",
    endDate: "Oct 7",
    price: 136,
    img: AIRBNBimages.image1,
    rating: "5.0",
  },
  {
    id: 2,
    title: "Lekki, Nigeria",
    distanceAway: 7,
    startDate: "Aug 7",
    endDate: "Aug 12",
    price: 342,
    img: AIRBNBimages.image2,
    rating: "5.0",
  },
  {
    id: 3,
    title: " Accra, Ghana",
    distanceAway: 393,
    startDate: "Sept 30",
    endDate: "Oct 7 2",
    price: 685,
    img: AIRBNBimages.image3,
    rating: "5.0",
  },
  {
    id: 4,
    title: " Fatick, Senegal",
    distanceAway: 2354,
    startDate: "Sept 30",
    endDate: "Sept 8",
    price: 145,
    img: AIRBNBimages.image4,
    rating: "5.0",
  },

  {
    id: 5,
    title: " Ngaparou, Senegal",
    distanceAway: 2403,
    startDate: "Sept 30",
    endDate: "Oct 7 2",
    price: 136,
    img: AIRBNBimages.image5,
    rating: "5.0",
  },

  {
    id: 6,
    title: " Ngaparou, Senegal",
    distanceAway: 2403,
    startDate: "Sept 30",
    endDate: "Oct 7 2",
    price: 136,
    img: AIRBNBimages.image6,
    rating: "5.0",
  },
  {
    id: 7,
    title: " Ngaparou, Senegal",
    distanceAway: 2403,
    startDate: "Sept 30",
    endDate: "Oct 7 2",
    price: 136,
    img: AIRBNBimages.image7,
    rating: "5.0",
  },

  {
    id: 8,
    title: " Ngaparou, Senegal",
    distanceAway: 2403,
    startDate: "Sept 30",
    endDate: "Oct 7 2",
    price: 136,
    img: AIRBNBimages.image8,
    rating: "5.0",
  },

  {
    id: 9,
    title: " Ngaparou, Senegal",
    distanceAway: 2403,
    startDate: "Sept 30",
    endDate: "Oct 7 2",
    price: 136,
    img: AIRBNBimages.image9,
    rating: "5.0",
  },

  {
    id: 10,
    title: " Ngaparou, Senegal",
    distanceAway: 2403,
    startDate: "Sept 30",
    endDate: "Oct 7 2",
    price: 136,
    img: AIRBNBimages.image10,
    rating: "5.0",
  },
  {
    id: 11,
    title: " Accra, Ghana",
    distanceAway: 393,
    startDate: "Sept 30",
    endDate: "Oct 7 2",
    price: 685,
    img: AIRBNBimages.image3,
    rating: "5.0",
  },
  {
    id: 12,
    title: " Fatick, Senegal",
    distanceAway: 2354,
    startDate: "Sept 30",
    endDate: "Sept 8",
    price: 145,
    img: AIRBNBimages.image4,
    rating: "5.0",
  },
  {
    id: 13,
    title: " Ngaparou, Senegal",
    distanceAway: 2403,
    startDate: "Sept 30",
    endDate: "Oct 7 2",
    price: 136,
    img: AIRBNBimages.image10,
    rating: "5.0",
  },
  {
    id: 14,
    title: " Warri, Nigeria",
    distanceAway: 393,
    startDate: "Sept 30",
    endDate: "Oct 7 2",
    price: 685,
    img: AIRBNBimages.image3,
    rating: "5.0",
  },
  {
    id: 15,
    title: " Abuja, Nigeria",
    distanceAway: 2354,
    startDate: "Sept 30",
    endDate: "Sept 8",
    price: 145,
    img: AIRBNBimages.image4,
    rating: "5.0",
  },
];

export default HomesData;
